encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("wiki/", views.index, name="index"),
    path("wiki/add/", views.add, name="add"),
    path("wiki/edit/", views.edit, name="edit"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/random_page/", views.random_page, name="random_page"),
    path("wiki/save/", views.save, name="save"),
    path("wiki/search/", views.search, name="search")
    ]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

encyclopedia/views.py
from django.shortcuts import render
from . import util
from markdown2 import Markdown
import random

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def convert_md_to_html(title):
    content = util.get_entry(title)
    markdowner = Markdown()
    if content == None:
        return None
    else:
        return markdowner.convert(content)

def add(request):
    if request.method == "GET":
        return render(request, "encyclopedia/add.html")
    else:
        title = request.POST["title"]
        content = request.POST["content"]
        title_exists = util.get_entry(title)
        if title_exists is not None:
            return render(request, "encyclopedia/error.html", {
                "error_message" : "Encyclopedia page already exists."
            })
        else:
            util.save_entry(title, content)
            html_content = convert_md_to_html(title)
            return render(request, "encyclopedia/entry.html", {
                'title' : title,
                'content' : html_content
            })

def edit(request):
    if request.method == "POST":
        title = request.POST['entry_title']
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title" : title,
            "content" : content
        })

def entry(request, title):
    html_content = convert_md_to_html(title)
    if html_content == None:
        return render(request, "encyclopedia/error.html", {
            "error_message" : "The requested page was not found."
        })
    else:
        return render(request, "encyclopedia/entry.html", {
            "title" : title,
            "content" : html_content
        })

def random_page(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    html_content = convert_md_to_html(random_entry)
    return render(request, "encyclopedia/entry.html", {
        "title" : random_entry,
        "content" : html_content
    })

def save(request):
    if request.method == "POST":
        title = request.POST['title']
        content = request.POST['content']
        util.save_entry(title, content)
        html_content = convert_md_to_html(title)
        return render(request, "encyclopedia/entry.html", {
            'title' : title,
            'content' : html_content
        })

def search(request):
    if request.method == "POST":
        search_entry = request.POST['q']
        entry_data = convert_md_to_html(search_entry)
        if entry_data is not None:
            return render(request, "encyclopedia/entry.html", {
                "title" : entry_data, 
                "content" : entry_data
            })
        else:
            entries = util.list_entries()
            suggestion = []
            for entry in entries:
                if search_entry.lower() in entry.lower():
                    suggestion.append(entry)
            return render(request, "encyclopedia/search.html", {
                "suggestion" : suggestion
        })

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <form action="{% url 'encyclopedia:add' %}" method="post">
        {% csrf_token %}
        <label>Title:</label><br>
        <input type="text" name="title" placeholder="Add title"><br>
        <p></p>
        <label>Content:</label><br>
        <textarea name="content" maxlength="2048" placeholder="Add text"></textarea><br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <form action="{% url 'encyclopedia:save' %}" method="post">
        {% csrf_token %}
        <label>Title:</label><br>
        <input type="text" name="title" value="{{ title }}"><br>
        <p></p>
        <label>Content:</label><br>
        <textarea name="content" maxlength="2048">{{ content }}</textarea><br>
        <input type="submit" value="Edit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Encyclopedia entry</h1>
    
    {{ content | safe }}

    <form action="{% url 'encyclopedia:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="entry_title" value="{{ title }}">
        <input type="submit" value="Edit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Error</h1>
        <h2>{{ error_message }}</h2>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Entries</h1>

    <ul>
        {% for entry in suggestion %}
            <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    
{% endblock %}